### ISSUE TITLE
Feature: Syntax for map types with arbitrary keys

### ISSUE THREAD

**Issue by kael-shipman** [brentropy/only-nested#3]
Currently there is no way to specify map types with arbitrary keys, such as

```typescript
type MappedType = {
  [k: string]: {
    one: number;
    two: boolean;
  }
}
```

I propose that for the following allowlist:

```typescript
const allowed = {
  [Symbol.for('key')]: {
    one: null,
    two: null,
  },
  knownKey: {
    something: null,
    otherThing: null,
  }
}
```

This assertion should pass:

```typescript
const val = {
  a: { one: 1, two: 2 },
  b: { one: 3, two: 4, three: 5 },
  c: { four: 4, five: 5 },
  knownKey: { something: true, otherThing: false, invalidThing: 1000 },
  unknownKey: 'some value',
}
const expected = {
  a: { one: 1, two : 2 },
  b: { one: 3, two: 4 },
  knownKey: { something: true, otherThing: false },
};
expect(only(allowed, val)).toMatchObject(expected);
```

There are several edge cases not described by the test above, and those should continue to work as they currently do.

Note the introduction of the special key `Symbol.for('key')`, which drives this functionality.

**Comment by brentropy** [comment]
I merged your PR adding this feature. It is now available in `v0.4.0`. Thanks.
